### ISSUE TITLE
Measure validation

### ISSUE THREAD

**Issue by SeanWheelwright** [DBCG/cql-evaluator#119]
Measure evaluation in the CQL Evaluator generally requires measure to conform to the CQF measures profile. Add validation for measure resources and report to use any validation errors.

More context: The CQF Measures IG specifies certain requirements that are more stringent for Measure resources than the base FHIR spec. In particular, certain elements like Groups, Stratifiers, and SDEs require unique "ids" for each element. For example, an SDE that collects Race demographic information may have the id "sde-race", the initial population for the first group element may have the id "group-1-initial-pop", etc. It's not necessary that the ids be human readable, but it is useful. The ids are required to support certain extensions in the MeasureReport, which tie Resources and other results back to the specific elements of the Measure resource that created or evaluated those. For example, if the InitialPopulation referenced several Encounters, each Encounter in the evaluatedResources section of the MeasureReport would have an extension that was like { URL : "sourceCriteria", value: "group-1-initial-pop" } and so on.

Acceptance Criteria:
Should be optional.
Should use the actual cqf-measures profile definition to stay in sync as a default. ~Should be configurable to use other profiles as needed.~
Should validate as first step of evaluation.
Should return a reasonable error if profile is not matched

**Comment by JPercival** [comment]
In particular, we need to ensure that SDEs, Groups, and Stratifiers need Ids.

**Comment by JPercival** [comment]
Resolved by #189
