### ISSUE TITLE
Bundled resources with urn's not accessible

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql-evaluator#28]
When accessing a bundle directly, if the fullUrl is a urn, the loaded resource has an "id" that includes the prefix, which means the provider resolution doesn't see it.

This is related to HAPI issues here:
https://github.com/hapifhir/hapi-fhir/blob/cbb16ce3affd3fc53dcbfe98dd3181644fe68604/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java#L639

https://github.com/hapifhir/hapi-fhir/issues/1868
https://github.com/hapifhir/hapi-fhir/issues/2057

**Comment by JPercival** [comment]
Resolved by #29
