### ISSUE TITLE
UUIDs in bundles do not resolve when a FHIR Bundle is loaded...

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql-evaluator#32]
Given an `Observation.subject` reference like this in a Bundle:

```
"subject": {
  "reference": "urn:uuid:0ae954fa-eff8-0d38-c840-3af401abc9fd"
},
```

The evaluator/engine doesn't retrieve the Observation. The FileDataProvider should probably ignore the urn:uuid: scheme just like the bundle retrieve loader does for the patient id.

**Comment by citizenrich** [comment]
There seems to be an issue in addition to the above. Observations are still not being processed correctly. For a reproducible example, see this repo with the fix to Observation resources and the lack of parsing still exists: https://github.com/citizenrich/hiv-indicators/tree/with_synthea_hiv_data
