### ISSUE TITLE
Remove HAPI dependency from evaluator.measure

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql-evaluator#43]
The MeasureEvaluation class in the `evaluator.measure` module does an excellent job of staying model agnostic all the way up to the point where it links some of the parameterized types to HAPI's IBase interface. In order to implement this for a different model (e.g. the IBM FHIR model objects), I would need for that base class to either be parameterized or just left out entirely. It would also be helpful to have the implementations in a separate module from the common classes so that consumers don't pick up a stray HAPI dependency.

**Comment by JPercival** [comment]
Resolved by #44 

Ongoing work with #57 to make this better going forward
