### ISSUE TITLE
No main manifest attribute

### ISSUE THREAD

**Issue by srini-vela** [DBCG/cql-evaluator#65]
When I tried to run **help** on evaluator.cli, got the following message:

**no main manifest attribute, in ./evaluator.cli/target/evaluator.cli-1.3.1-SNAPSHOT.jar**

**Comment by imranq2** [comment]
This is usually because the shade-plugin is not working (this sets the main class in the manifest).  Looks to be an issue in pom.xml.  if you build "ci" then it works.

**Comment by srini-vela** [comment]
Thanks for the response. Not sure that I understood the solution. What corrections that I need to make to pom.xml so that I can create a successful jar, that works!

**Comment by JPercival** [comment]
I removed the `ci` profile since it was tripping devs up. Just run "package" as normal and you'd get a shaded jar. No need to edit the pom.

`java -jar ./evaluator.cli/target/evaluator.cli-1.4.1-SNAPSHOT-shaded.jar`
