### ISSUE TITLE
Cannot cast a value of type java.util.ArrayList as org.opencds.cqf.cql.engine.runtime.Tuple 

### ISSUE THREAD

**Issue by azhar0287** [DBCG/cql-evaluator#88]
Hi Everyone. 
We are trying to evaluate the "BCSE HEDIS MY2022" measure using Cql Evaluator and facing this issue. @brynrhodes @JPercival  @jreyno77 can you please look into this?

**Comment by TalhaBinAhmed255** [comment]
/*
Use this version of the function as a workaround for an issue in the JavaScript execution engine:
define function "VS Cast Function"(VSet List<System.Code>):
  ( ( cast { "VSet", 1 }[0]as Tuple {
      codes List<System.Code>,
      oid System.String,
      version System.String
    }
  ).codes ) VSetCodes
    return System.Code { code: VSetCodes.code, system: VSetCodes.system }
*/

/*
In the Java engine, this workaround is unnecessary

See this Gist for discussion:
https://gist.github.com/mattwiller/d008bc7a88d9a17675fddbc95b99403e
*/
define function "VS Cast Function"(VSet List<System.Code>):
  VSet
